dse_user: 'cassandra'
cassandra_dir: '/etc/dse/cassandra'
dse_install_dir: '/etc/dse'
dse_default_dir: '/etc/default'
cluster_name: 'prod_dse'
data_dir: '/data/data'
hints_dir: '/data/hints'
cl_dir: '/data/CL'
cdc_raw: '/data/CDC'
scd_dir: '/data/SCD'
seed_nodes: '<list your seed nodes'
numtoken: '8'
dse_yaml: 'dse.yaml_prod'
cassandra_yaml: 'cassandra_prod.yaml'

